### ISSUE TITLE
Homepage statistics based on role (loose idea)

### ISSUE THREAD

**Issue by sungraze** [occrp/id-frontend#8]
It would make sense to display different things on the homepage (index) besides the list of relevant tickets, depending on role. Ideas:

### requesters 
For a new user, an empty table would make no sense. Some kind of shortcut/callout to ticket creation might make sense.
Another idea is to have king of progress (activity) tracker for relevant tickets. "Activity since you've last logged in"

### staff and/or admin

Same as above, activity since last login. For admins it could include data across various tickets & responders. Might intersect with the data from the eventual /statistics.

**Comment by stas** [comment]
Closed in favour of #12 and https://github.com/occrp/id-backend/issues/42
